# your override should supply an envName
envName: jenana

# if set, override all Applications to use this project
#projectOverride: null


#default:
  #app:
    #enableAutoSync: null
    #autoSyncPrune: true
    #destination:
      #namespace: null
      #server: null
    #project: null
    #source:
      #path: null
      #repoURL: null
      #targetRevision: HEAD

      #extraSourceFields: |
        #helm:
          #valueFiles:
          #- {{ $.Values.envName }}-values.yaml
      #  kustomize:
      #    namePrefix: prod-
    #extraFields: |
    #  Default fields you want on all applications, unless the app individually overrides


applications:

  helm-guestbook:
    enabled: true
    destination:
      namespace: my-apps
      server: "https://kubernetes.default.svc"
    source:
      targetRevision: HEAD
      path: helm-guestbook
      repoURL: "https://github.com/Jena98/argocd-helm-app-of-apps-example.git"


